config/routes.rb
MizeCraft::Application.routes.draw do

  root to: 'static_pages#index'
  resources :static_pages, only: [:show, :index]
  resources :pages, only: [:new, :show, :create, :index]
  match "/auth/:provider/callback" => "sessions#create"
  match "/auth/failure" => "sessions#failure"
  match "/signout" => "sessions#destroy", :as => :signout

end

app/models/page.rb
class Page < ActiveRecord::Base
  include Scraper
  include Scraper::Result
  
  attr_accessible :content, :original_url, :title, :user_id
  before_create :get_title, :get_content

end

app/models/page_test.rb
class PageTest < ActiveRecord::Base
  attr_accessible :page_id
  belongs_to :page

  serialize :test_results, Hash
  after_create :run_test_suite

  include Analyzer



end

app/models/test.rb
class Test < ActiveRecord::Base

  belongs_to :page

  def page
    @page ||= Page.find(self.page_id)
  end

  def run_test_suite
    self.h1_presence_test
    self.save
  end

  def h1_presence_test
    case page.number_of_h1
    when 0
      output = "You don't have any h1 tags. They're important."
      result = false
    when 1
      output = "You have the correct number of h1 tags."
      result = true
    else
      output = "You have too many h1 tags."
      result = false
    end
    self.h1_presence_result = result
    self.h1_presence_output = output
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.oauth_token = auth.credentials.token
      user.oauth_token_secret = auth.credentials.secret
    end
  end
  
  def tumblr_client
    @client ||= Tumblr::Client.new(
      consumer_key: ENV['TUMBLR_KEY'],
      consumer_secret: ENV['TUMBLR_SECRET'],
      oauth_token: self.oauth_token,
      oauth_token_secret: self.oauth_token_secret
    )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def new
    @page = Page.new
  end

  def create
    @page = Page.create(original_url: params[:original_url], user_id: current_user.id)
    PageTest.create(page_id: @page.id)
    redirect_to page_path(@page)
  end

  def show
    @page = Page.find(params[:id])
    @test = PageTest.where(page_id: @page.id).last
    @page.title
  end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to new_page_path, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end

  def failure
    redirect_to root_url, :notice => "You were denied authentication."
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
  end

end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  def create
    @test = Test.new(page: @page)
    @test.run_test_suite
    @test.save
  end

end

app/controllers/users_controller.rb
 class UsersController < ApplicationController

  before_filter :check_user, only: [:new]

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to new_page_path
    else
      redirect_to root_url
    end
  end

  private

  def check_user
    redirect_to new_page_path if current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/page_tests_helper.rb
module PageTestsHelper

  def keyword_observations
    keywords = @test.keywords
    "#{keywords[0].capitalize}, #{keywords[1]}, #{keywords[2]}, #{keywords[3]}, and #{keywords[4]}."
  end

  def word_count_observations
    "Your piece is approximately #{@page.word_count} words long."
  end

  def join_messages(messages)
    "<ul><li>" + messages.join("</li><li>") + "</li></ul>"
  end

  def title_keywords_messages
    messages = []
    messages << @test.title_includes_keywords_test
    join_messages(messages) + title_why_matters
  end

  def title_keywords_results
    @test.test_results[:title_keyword_result]
  end

  def title_why_matters
    "<span class='why'><strong><u>Why this matters:</u></strong> Your title tag is crucial for letting search engines know what your content is about. It also provides the text that shows up at the top of the browser window.</span>"
  end

  def url_keywords_messages
    messages = []
    messages << @test.url_includes_keywords_test
    join_messages(messages) + url_why_matters
  end

  def url_keywords_results
    @test.test_results[:url_keyword_result]
  end

  def url_why_matters
    "<span class='why'><strong><u>Why this matters:</u></strong> URLs that describe your site content in plain English provide search engines (and users) with more clues about what your post is about.</span>"
  end

  def word_count_messages
    messages = []
    messages << @test.word_count_test
    join_messages(messages) + word_count_why_matters
  end

  def word_count_results
    @test.test_results[:word_count_result]
  end

  def word_count_why_matters
    "<span class='why'><strong><u>Why this matters:</u></strong> Search engines favor content that has between 300 and 600 words.</span>"
  end

  def h1_messages
    messages = []
    messages << @test.h1_presence_test
    join_messages(messages) + header_why_matters
  end

  def h2_messages
  end

  def h3_messages
  end

  def header_results
    @test.test_results[:h1_presence_result]
  end

  def header_keyword_results
    @test.test_results[:h1_keyword_result]
  end

  def h1_keyword_messages
    messages = []
    messages << @test.h1_keywords_test
    join_messages(messages) + header_why_matters
  end

  def header_why_matters
    "<span class='why'><strong><u>Why these matter:</u></strong> Like the title tag, header tags (h1, h2, etc) provide an important cue for search engines about the content of your piece.</span>"
  end

  def image_messages
    messages = []
    messages << @test.number_of_body_images_test
    join_messages(messages) + image_why_matters
  end

  def image_results
    @test.test_results[:number_of_body_images_result]
  end

  def image_alt_results
    @test.test_results[:alt_tags_presence_result]
  end

  def image_alt_keyword_results
    @test.test_results[:alt_tags_keyword_result]
  end

  def image_why_matters
    "<span class='why'><strong><u>Why these matter:</u></strong> Images do more than make your page look cool. If you include 'alt' descriptions, they also give search engines further insight into your post.</span>"
  end

  def image_alt_messages
    messages = []
    messages << @test.image_alt_tags_presence_test
    join_messages(messages) + image_why_matters
  end

  def image_alt_keyword_messages
    messages = []
    messages << @test.image_alt_tags_keywords_test
    join_messages(messages) + image_why_matters
  end

  def broken_links_messages
    messages = []
    messages << @test.broken_links_test
    join_messages(messages) + link_why_matters
  end

  def broken_links_results
    @test.test_results[:broken_links_result]
  end

  def link_why_matters
    "<span class='why'><strong><u>Why these matter:</u></strong> As search engines scan your content, external pages that you link to give them further information about what you're describing. Links to other pages within your site also add to what the engine knows about your site as a whole.</span>"
  end

  def content_body_messages
    messages = []
    messages << @test.keyword_saturation_test
    join_messages(messages) + content_body_why_matters
  end
  
  def content_body_results
    @test.test_results[:keyword_saturation_result]
  end

  def content_body_why_matters
    "<span class='why'><strong><u>Why this matters:</u></strong> The bulk of your content is (or should) be in your &lt;p&gt; tags. Search engines don't place as much emphasis on this area as other tags, but content rich with keywords (particularly toward the beginning of your piece) still influence your search rating.</span>"
  end

  def first_150_words_results
    @test.test_results[:keywords_in_the_first_150_words_result]
  end

  def first_150_words_messages
    messages = []
    messages << @test.keywords_in_the_first_150_words_test
    join_messages(messages) + content_body_why_matters
  end
end

app/views/layouts/_navbar.html.erb
<div class="navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <% if current_user  %>
            <%= link_to 'siteKick', root_url, class: "logo" %>
          <div class="nav pull-right" style='padding-right:10px; padding-top:11px; margin-top: 3px; display:inline-block'>

          <% if params[:id] %>
            <a class="btn-info" style='margin-top: 3px; margin-right: 4px' href="javascript:void(0);" onclick="javascript:introJs().start();">tour the site</a>
          <% end %>
            <%= link_to "exit", "/signout", class: "btn-danger" %>
          </div>
          <div class="nav pull-right" style='padding-right:10px; padding-top:11px; margin-top: 3px; display:inline-block'>
            <%= link_to "posts", "/pages/new", class: "btn-info" %>
          </div>


          <% else %>
          <%= link_to 'siteKick', root_url, class: "logo" %>
          <div class="nav pull-right" style='padding:10px; margin-top: 5px; padding-top:11px'>
            <%= link_to "Get Started!", "/auth/tumblr", class: "btn-primary" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>siteKick</title>
  <%= stylesheet_link_tag :application %>
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tag %>
</head>
<body>

  <%= render 'layouts/navbar' %>
  <% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>

  <div class='container'>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>siteKick</title>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
  <%= stylesheet_link_tag :application %>
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tag %>
</head>
<body>


  <div class='container'>
    <%= yield %>
  </div>
  
</body>
</html>

app/views/layouts/static_pages.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>siteKick</title>
  <%= stylesheet_link_tag :static %>
  <%= javascript_include_tag :application %>

  <%= csrf_meta_tag %>
</head>
<body>
 <%= render 'layouts/navbar' %>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/_checkbox.html.erb
<div class = 'hidden'>
  <span class='title_field'><%= title_keywords_results %></span>
  <span class='url_field'><%= url_keywords_results %></span>
  <span class='word_count_field'><%= word_count_results %></span>
  <span class='header_field'><%= header_results %></span>
  <span class='header_keyword_field'><%= header_keyword_results %></span>
  <span class='image_field'><%= image_results %></span>
  <span class='image_alt_field'><%= image_alt_results %></span>
  <span class='image_alt_keyword_field'><%= image_alt_keyword_results %></span>
  <span class='broken_links_field'><%= broken_links_results %></span>
  <span class='content_body_field'><%= content_body_results %></span>
  <span class='first_150_field'><%= first_150_words_results %></span>
</div>

app/views/pages/_progress2.html.erb
<% @test_percent = (@test.number_of_tests_passed*100)/@test.number_of_tests_evaluated %>
<% if @test_percent < 50 %>
  <% my_class = "progress-bar-danger" %>
<% elsif @test_percent < 80 %>
  <% my_class = "progress-bar-warning" %> 
<% else %>
  <% my_class = "progress-bar-success" %>
<% end %>

<div class="progress progress-striped active"><div class="progress-bar <%= my_class %>"  role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: <%= @test_percent %>%"></div></div>

app/views/pages/new.html.erb
<%= render 'layouts/navbar' %>

<%= javascript_include_tag :application %>
<%= stylesheet_link_tag :bootstrap_overwriting %>
<%= csrf_meta_tag %>

<div class="container-links">
  <div class='well'>
    <% if current_user %> 
    
    <% posts = current_user.tumblr_client.posts("#{current_user.uid}.tumblr.com")['posts'] %>
    
    <% img_src = current_user.tumblr_client.avatar("#{current_user.uid}.tumblr.com") %>

    <div class='row'>

      <div class='col-xs-4 col-sm-2 col-md-2'>
        <center><%= image_tag(img_src, :size => "90x90", :class => 'img-circle')%></center>
      </div>

      <div class='col-xs-4 col-sm-2 col-md-2'><center>
        <div class="new-text">
         <em>Hey, <%= current_user.tumblr_client.blog_info("#{current_user.uid}.tumblr.com")['blog']['name'] %>!</em>
       </div></center>
     </div>

     <div class='col-xs-2 col-sm-2 col-md-2'>
     </div>

     <div class="clearfix visible-xs"></div>

     <div class='col-xs-4 col-sm-2 col-md-2'>
      <div class='small-text' style='text-align:right'><div class='label label-success'><%= followers = current_user.tumblr_client.followers("#{current_user.uid}.tumblr.com")['total_users'] %></div><br>
      <div class='label label-warning'><%= likes = current_user.tumblr_client.likes['liked_count'] %></div> </div>
    </div>

    <div class='col-xs-4 col-sm-2 col-md-2'>
     <div class='big-text'>Followers<br>Likes</div>
   </div>
 </div>

 <div class='row'>

  <div class='col-xs-6 col-sm-4 col-md-4'>
  </div>

  <div class="clearfix visible-xs"></div>


  <div class='col-xs-6 col-sm-4 col-md-4'><div class='new-text'>
    <div class='glyphicon glyphicon-chevron-down'></div></div>

  </div>

  


  <div class='col-xs-6 col-sm-4 col-md-4'><div class='new-text'>
    <div class='glyphicon glyphicon-chevron-down'></div></div>
  </div>

  


</div>

<div class='well'>
  
  <div class = 'links'>

    <% posts.each do |post| %>

    <% if post['type'] == 'text' %>

    <%= button_to post['title'], pages_path(@page, original_url: post['post_url']), :action => "create", :method => "post", :class => 'btn btn-primary btn-lg btn-block' %><br>

    <% end %>

    <%end %>
    
  </div>    
  <% end %>
</div>
</div>
</div>
<footer>
  <center> <p>© siteKick 2013</p></center>
</footer>

app/views/pages/show.html.erb
<%= render 'layouts/navbar' %>

<div id = 'page_show_container'>

  <div class='well' style='border-radius:10px; background-color:rgba(255,255,255,0.4)'>

<center>

<%= render 'progress2' %>


<h2>Your site rated<div style='color:red'> <%= @test.number_of_tests_passed %></div> out of a possible <%= @test.number_of_tests_evaluated %>.</h2>


</center>
</div>

  <div class = 'row'>
    <div class='feedback col-md-4' data-step="1" data-intro="Here are your SEO test results. Click on each header to receive more detailed feedback about how your posts can be optimized for search results." data-position="right">
      <div id ='accordion'>

        <p class="title-tag"> Title Tag <%= image_tag "check1.png", :class => 'title_check check' %></p>
        <div>
          <p class='main_messages'><%= title_keywords_messages.html_safe %>
          </p>
        </div>

        <p class = "url-tag"> URL <%= image_tag "check1.png",:class => 'url_check check' %></p>
        <div>
          <p class='url_messages'><%= url_keywords_messages.html_safe %>
          </p>
        </div>
        <p class="word-tag"> Word Count <%= image_tag "check1.png", :class => 'word_count_check check' %></p>
        <div>
          <p class='word_count_messages'><%= word_count_messages.html_safe %>
          </p>
        </div>
        <p class="header-tag"> Header Tags  <%= image_tag "check1.png", :class => 'header_check check' %></p>
        <div>
          <span class='h1_messages'><%= h1_messages.html_safe %>
          </span>
        </div>
        <p class="header-keyword-tag"> Header Keywords  <%= image_tag "check1.png", :class => 'header_keyword_check check' %></p>
        <div>
          <span class='h1_messages'><%= h1_keyword_messages.html_safe %>
          </span>
        </div>
        <p class="image-tag"> Images <%= image_tag "check1.png", :class => 'image_check check' %></p>

        <div>
          <p class='image_messages'><%= image_messages.html_safe %>
          </p>
        </div>
        <p class="image-alt-tag"> Image Alt Descriptions <%= image_tag "check1.png", :class => 'image_alt_check check' %></p>

        <div>
          <p class='image_alt_messages'><%= image_alt_messages.html_safe %>
          </p>
        </div>
        <p class="image-alt-keyword-tag"> Image Alt Keywords <%= image_tag "check1.png", :class => 'image_alt_keyword_check check' %></p>

        <div>
          <p class='image_alt_keyword_messages'><%= image_alt_keyword_messages.html_safe %>
          </p>
        </div>
        <p class = "link-tag"> Links <%= image_tag "check1.png", :class => 'broken_links_check check' %></p>

        <div>
          <p class='link_messages'><%= broken_links_messages.html_safe %>
          </p>
        </div>
        <p class="content-saturation-tag"> Keyword Saturation <%= image_tag "check1.png", :class => 'content_body_check check'  %></p>

        <div>
          <span class='content_body_messages'><%= content_body_messages.html_safe %>
          </span>
        </div>
        <p class="content-tag"> First 150 Words <%= image_tag "check1.png", :class => 'first_150_check check'  %></p>
        <div>
          <span class='content_body_messages'><%= first_150_words_messages.html_safe %>
          </span>
        </div>
      </div>
    </div>

    <div class='article_content col-md-7 col-md-offset-1' data-step="2" data-intro=" We've summarized key data points about your post that search engines care about. These points provide a handy reference as you optimize your content for search engine results." data-position="left">
      <div class='post_data'>
        <p class="keywords"><strong>Keywords:</strong> <%= keyword_observations %></p>
        <p class="title"><strong>Title: </strong>&lt;title&gt;<%= @page.title %>&lt;/title&gt;</p>
        <p class="url"><strong>URL: </strong><%= @page.original_url %>
        <p class="h1_tags"><strong>H1 tags: </strong><%= @page.h1_text_display %>
        <p class="word"><strong>Word Count:</strong> <%= @page.word_count %></p>
      </div>
      <div class="original-article" data-step="3" data-intro="This is your original post. As you click through the results of our test, relevant sections will be highlighted to make it easier to integrate our feedback into your content." data-position="left">
        <%= @page.content.html_safe %>
      </div>
    </div>
  </div>

</div>

<%= render 'checkbox' %>

<footer>
  <center>© siteKick 2013</center>
</footer>

app/views/static_pages/index.html.erb
  <title>siteKick</title>
  <link rel="stylesheet" href= "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
  
  <%= javascript_include_tag :application %>
  <%= stylesheet_link_tag :bootstrap_overwriting %>
  <%= csrf_meta_tag %>


  <%= render 'layouts/navbar' %>

  <div class="container">

    <div class="hero-unit">
      <div class="text-hero-unit">
        
        <p class='welcome_message'>
          Kick up your site's search<br> results with siteKick!</p>
          
          
          <div class="push">
          </div>
        </div>
      </div>

      <div class="row"><center>
        <div class="col-md-6">

          <div class='well'><p class='glyphicon glyphicon-cloud-download' style='font-size:32px'></p><br><p class='big-text'>siteKick grabs your Tumblr blog.</p></div>
          <div class='well'><p class='glyphicon glyphicon-check' style='font-size:32px'></p><br><p class='big-text'>Suggests improvements.</p></div>

          
        </div>

        <div class="col-md-6">
          <div class='well'><p class='glyphicon glyphicon-search' style='font-size:32px'></p><br><p class='big-text'>Analyzes its web searchability.</p></div>
          <div class='well'><p class='glyphicon glyphicon-eye-open' style='font-size:32px'></p><br><p class='big-text'>Gets you more views.</p></div>
        </div></center>

      </div>

      <footer>
        <center>© siteKick 2013</center>
      </footer>